name: Test Coverage

on:
  pull_request:
    branches: 
      - 'dev'
    paths:
      - '**.java'

permissions:
  contents: read
  pull-requests: write

env:
  wd: ./backend

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Coverage
      working-directory: ${{ env.wd }}
      run: |
        chmod +x gradlew
        ./gradlew testCoverage

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/backend/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 📊 테스트 커버리지 결과
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        update-comment: true
        continue-on-error: true
